
module.exports = {
    "Basic Materials": '',
    "Basic Resources": '',
    "Forest Products and Paper": '',
    "Forest Products": '',
    "Paper Products": '',
    "Mining and Metals": '',
    "Aluminum": '',
    "Mining": '',
    "Non Ferrous Metals": '',
    "Precious Metals": '',
    "Steel": '',
    "Chemicals": '',
    "Chemicals Commodity": '',
    "Chemicals Specialty": '',
    "Consumer Cyclical": '',
    "Automobiles": '',
    "Auto Parts and Tires": '',
    "Automobile Manufacturer": '',
    "Cyclical Goods and Services": '',
    "Airlines": '',
    "Home Construct and Furnish": '',
    "Furninshing and Appliances": '',
    "Home Construction": '',
    "Leisure Goods and Service": '',
    "Casinos": '',
    "Consumer Electronics": '',
    "Lodging": '',
    "Recreation Prod and Service": '',
    "Restaurants": '',
    "Toys": '',
    "Textile and Apparel": '',
    "Clothing and Fabric": '',
    "Footwear": '',
    "Media": '',
    "Advertising": '',
    "Broadcasting": '',
    "Entertainment": '',
    "Publishing": '',
    "Retail": '',
    "Retailers Apparel": '',
    "Retailers Broadline": '',
    "Retailers Drug-Based": '',
    "Retailers Specialty": '',
    "Consumer Noncyclical": '',
    "Food and Beverage": '',
    "Beverage": '',
    "Distillers and Brewers": '',
    "Soft Drinks": '',
    "Food": '',
    "Food Products": '',
    "Noncyclical Goods and Svcs": '',
    "Consumer Services": '',
    "Cosmetics": '',
    "Food Retailers, Wholesalers": '',
    "Household Products": '',
    "Household Products Durable": '',
    "Household Products Non Durable": '',
    "Tobacco": '',
    "Energy": '',
    "Coal": '',
    "Oil Companies Major": '',
    "Oil Companies Secondary": '',
    "Oil Drilling, Equipment Svcs": '',
    "Pipelines": '',
    "Financial": '',
    "Banks": '',
    "Banks, Ex S&L": '',
    "Savings & Loan": '',
    "Financial Services": '',
    "Diversified Financial": '',
    "Real Estate": '',
    "Investment Services": '',
    "Insurance": '',
    "Insurance Full Line": '',
    "Insurance Life": '',
    "Insurance Property Casualty": '',
    "Healthcare": '',
    "Biotechnology": '',
    "Healthcare Providers": '',
    "Medical Products": '',
    "Advance Medical Devices": '',
    "Medical Supplies": '',
    "Pharmaceuticals": '',
    "Industrial": '',
    "Construction": '',
    "Building Materials": '',
    "Heavy Construction": '',
    "Industrial Goods & Svcs": '',
    "Advanced Industrial Equip": '',
    "Aerospace": '',
    "Containers & Packaging": '',
    "Electronic Components & Equip": '',
    "General Industrial Svcs": '',
    "Industrial Services": '',
    "Pollution Control": '',
    "Industrial Equipment": '',
    "Factory Equipment": '',
    "Heavy Machinery": '',
    "Industrial Transportation": '',
    "Air Freight": '',
    "Land Transportation": '',
    "Marine Transportation": '',
    "Railroads": '',
    "Trucking": '',
    "Transportation Services": '',
    "Industrial Diversified": '',
    "Technology": '',
    "Communications Technology": '',
    "Semiconductors": '',
    "Software": '',
    "Technology Hardware Equip": '',
    "Computers": '',
    "Office Equipment": '',
    "Technology Services": '',
    "Diversified Technology Svcs": '',
    "Internet Services": '',
    "Telecommunications": '',
    "Fixed Line Communications": '',
    "Wireless Communications": '',
    "Utilities": '',
    "Electric Utilities": '',
    "Gas Utilities": '',
    "Water Utilities": '',
}